### ISSUE TITLE
Improving development experience: how to debug schematics

### ISSUE THREAD

**Issue by Andrei0872** [retarsis/routerkit#54]
### What is this feature?

This _feature_ does not directly concern the users of the library, but its developers/contributors.

### How the feature should work?

This feature aims to improve the development experience by providing an easy way to debug the library's schematics.

It can be achieved by creating a `.vscode/launch.json` file with the following content:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/node_modules/@angular/cli/bin/ng",
      "args": [ 
        // # 1
        // "add", 
        // // "@routerkit/core"
        // "./dist/routerkit/",
        // "--skipInstall",

       // # 2
        "g",
        "@routerkit/core:parse",
        "--project",
        "example-app",
      ],
      "sourceMaps": true,
      "outFiles": [
        "${workspaceFolder}/dist/routerkit/**/*.js"
      ],
      "outputCapture": "std"
    }
  ]
}
```

`# 1` and `# 2` could have their own launch configuration eventually.

In order to create the `dist/routerkit`, we need to run both `npm run build` and `npm run build:schematics`, because, in this case, the `parse` schematic relies on a (built) project. The first build command will build the project the schematic will be tested on and the second build command will build the schematics(with source maps).

Then, we can go to `parse/index.ts` and place a breakpoint there to see the results.

On a side note, I noticed that, during debugging, the `ora` package throws the following error: `cannot write after stream was close`. I think it's because it uses by default the `process.stderr` stream by default:

```typescript
const projectSpinner = ora(taskStart('Analyzing project')).start();
```

I got rid of the error by instantiating the spinner like this:

```typescript
const projectSpinner = ora({ text: taskStart('Analyzing project'), stream: process.stdout }).start();
```

### Is your feature request related to a problem?

No.

I think we could add the necessary steps in the CONTRIBUTING.md file. Also, it would be my pleasure to create a PR for this, if everything is alright.

**Comment by retarsis** [comment]
so, is your suggestion to add `.vscode/launch.json` and modify `ora` (change stream)?

**Comment by retarsis** [comment]
anyway, let's proceed with a pull request
